version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest

    branches:
      only:
        - master

    steps:
      - checkout

      - restore_cache:
          key: v1-cache-{{ checksum "yarn.lock" }}

      - run:
          name: install
          command: yarn

      - save_cache:
          key: v1-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: test
          command: npm run test:cov

      - run:
          name: build
          command: npm run build

      - run:
          name: coverage
          command: npx codecov
