name: CI

on:
  push:
    branches:
      - master

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node Version
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: true
        run: npm run test

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node Version
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: true
        run: npm run test

  test-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 5

      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: true
        run: npm run test:cov

      - name: Coverage
        run: npx codecov
