name: CI

on:
  push:
    branches:
      - master

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build

  test-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: true
        run: npm run test:cov

      - name: Build
        run: npm run build

      - name: Coverage
        run: npx codecov
